### ISSUE TITLE
Didn't get it working on a Rasberry Pi

### ISSUE THREAD

**Issue by hankman13** [raphaelyancey/Virtual_FM_Band#1]
I love this project and I just want to build it like you mentioned it in your blogpost.

So I tried to set it up, but I'm failing to install portaudio on Raspberry Pi.
Maybe you could help to get this running.

Thank you!

**Comment by raphaelyancey** [comment]
Hi, thanks! I almost finished writing a step-by-step tutorial, it should be published in a few days on my blog.

Meanwhile, can you elaborate your setup ? Which Raspberry Pi and which Raspbian version ?

I guess you ran `apt-get install libportaudio0 libportaudio2 libportaudiocpp0 libmad0-dev portaudio19-dev libasound-dev` as mentionned in the README, did it go well ?

Where does the install fail exactly ?

**Comment by hankman13** [comment]
I'm using a **Raspberry Pi 3**. At the moment I don't have an USB Audio Dongle and the rotary encoders attached.
My Raspbian version is "based on 2017-11-29-raspbian-stretch", I updated all packages via apt-get.

 after `sudo apt-get install libportaudio0 libportaudio2 libportaudiocpp0 libmad0-dev portaudio19-dev libasound-dev`
the result is this:

`Note, selecting 'libasound2-dev' instead of 'libasound-dev'`
`E: Unable to locate package libportaudio0`
`E: Unable to locate package libportaudiocpp0`
`E: Unable to locate package libmad0-dev`
`E: Unable to locate package portaudio19-dev`

**Comment by raphaelyancey** [comment]
Did you run `sudo apt-get update` before? If not you should.

I just tried the following on a stock Raspbian Lite on Pi 3 and it worked fine:
```bash
sudo apt-get install -y --no-install-recommends git python-dev pulseaudio pulseaudio-utils libportaudio0 libportaudio2 libportaudiocpp0 libmad0-dev portaudio19-dev libasound-dev
```

**Comment by hankman13** [comment]
I retried and it seemed that it worked to install the base packages.
Only one note I got, is this:
`Note, selecting 'libasound2-dev' instead of 'libasound-dev'`

**Comment by raphaelyancey** [comment]
Great. I wrote an [install script](https://github.com/raphaelyancey/Virtual_FM_Band/blob/master/install.sh) for the incoming tutorial, successfully tested yesterday on a clean Raspbian Lite on a Pi 3. If you use it I'd love to hear if it went well too ([@raphaelyancey](https://twitter.com/raphaelyancey) or email).

I'm closing this issue since it's now working for you.
