### ISSUE TITLE
install.sh bugs

### ISSUE THREAD

**Issue by hankman13** [raphaelyancey/Virtual_FM_Band#2]
Hi, me again.
I justed started again on a fresh raspbian lite installation with an Raspberry Pi 3 with no additional hardware. I ran `sudo raspi-config` to change the default audio output to audio jack.

Then I copied your install script via:
`wget https://raw.githubusercontent.com/raphaelyancey/Virtual_FM_Band/master/install.sh`
and run `sh install.sh`

After the script told me to be finished I checked crontab via `crontab -l` but there was no entry.
So I started `crontab -e` and choose my editor (nano).
I re-runned the script it stopped by creating the existing folder audio. So I deleted the folder audio and app.
Now the script had no problem and the crontab was written. But a little typo `@reboot /usr/bin/env/bash /home/pi/pi/app/run.sh` so the "pi" was twice, I changed it manually.
So I copied 2 audio files (ch1.mp3 and ch2.mp3) into the audio folder.
I rebooted and hoped, that I can hear one of the channels. But unfortunately nothing happend.

I tried to run the `sh run.sh` and got the following screen:
```
pi@raspberrypi:~/app $ sh run.sh
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
INFO:root:Started swmixer
INFO:root:
Traceback (most recent call last):
  File "/home/pi/app/src/main.py", line 90, in <module>
    chn = snd.play(volume=1.0, loops=-1)
  File "/home/pi/app/src/swmixer.py", line 468, in play
    stream = _create_stream(self.filename, self.checks)
  File "/home/pi/app/src/swmixer.py", line 421, in _create_stream
    assert(mf.samplerate() == gsamplerate)
AssertionError
Unhandled exception in thread started by <function f at 0x75e96e30>
Traceback (most recent call last):
  File "/home/pi/app/src/swmixer.py", line 672, in f
    tick()
  File "/home/pi/app/src/swmixer.py", line 613, in tick
    while ginit and gstream.get_write_available() < gchunksize: time.sleep(0.001)
AttributeError: 'NoneType' object has no attribute 'get_write_available'
```
So I don't know what went wrong.

**Comment by raphaelyancey** [comment]
First I'd run the scripts with `bash` and not `sh`, that might explain the cron problem.

For the Python error, it might come from the hardcoded device ID (https://github.com/raphaelyancey/Virtual_FM_Band/blob/master/src/main.py#L28) which is `2` for the USB DAC.

Run [this Python snippet](https://stackoverflow.com/a/39677871/2544016) to list the devices and replace with the correct one (I guess it's `1` but I'm not sure).

**Comment by raphaelyancey** [comment]
And you're right, the script shouldn't be run twice in its actual state so be sure to remove `~/app` and `~/audio` before. By the way I fixed the `/pi/pi` typo, thanks.

**Comment by hankman13** [comment]
I will retry the next days and use a USB DAC and also my chinese mailbag with the rotary encoders arrived. I'm looking forward for the tutorial.

**Comment by hankman13** [comment]
So today I attached the USB DAC and started with a fresh rasbian image.
the Cron wasn't written by the script. So I started it manually.
It didn't run, so I tried to changed the `sudo nano /usr/share/alsa/alsa.conf` the card parameter from 0 to 1.
So I run the script again, the error now looks like that.

`pi@raspberrypi:~/app $ bash run.sh
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ERROR:root:Couldn't start swmixer:
INFO:root:
ERROR:root:Couldn't load /home/pi/audio/ch1.mp3:
ERROR:root:Couldn't load /home/pi/audio/ch2.mp3:
INFO:root:Virtual frequency changed to 1
INFO:root:['   ch1    ', '   ch2    ']
INFO:root:[]`

**Comment by raphaelyancey** [comment]
- Did you run the [Python snippet](https://stackoverflow.com/a/39677871/2544016) on the Pi for listing your audio devices?
- Did you report the audio device ID in [main.py](https://github.com/raphaelyancey/Virtual_FM_Band/blob/master/src/main.py#L28) if different than `2`?
- What is your USB DAC?

Also, I published the [tutorial](https://raphaelyancey.fr/2018/09/06/grand-theft-auto-radio-set-tutorial.html) if you want to take a look.

**Comment by hankman13** [comment]
Hi,
today I rebuild everything, added the switches and the USB DAC.
And it worked, with one exception the crontab entry was not written by the script.

And just as a note, I had trouble to connect die rotary encoders the right way but the link to the bmc numbers in the env file helped me just to rewire it right.

Everything runs nice.

Thank you, I love this project.

**Comment by raphaelyancey** [comment]
Congratulations on making it 👍 Glad it's working (almost) well.
I'll look into the cron issue.

I'd love to see a picture of your radio if you can get the time to do it :)

**Comment by hankman13** [comment]
At this time it looks like the schematic in your tutorial.
I hope that some new features will be planned like noise between channels so the real radio feelings comes up.
